# Installing Ubuntu 20.04 LTS as the base image
FROM ubuntu:20.04

# Setting environment variables
# Instructing apt to operate in non-interactive mode
ENV DEBIAN_FRONTEND=noninteractive

# Copying C++ code
COPY ./app/src/main/cpp/src/ /cpp/src
COPY ./app/src/main/cpp/CMakeLists.txt /cpp/CMakeLists.txt

# Setting the working directory
WORKDIR /cpp

# Running a command when the container starts
CMD ["/bin/bash"]